# Generated by Django 5.0.1 on 2024-02-18 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('tutor', '0002_tutor_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment_method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_fee', models.CharField(max_length=400)),
                ('discount', models.CharField(max_length=400)),
                ('cus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('tutor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.tutor')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.payment_method')),
            ],
        ),
    ]
