# Generated by Django 5.0.1 on 2024-02-19 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='v_c',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='v_status',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
