# Generated by Django 5.0.1 on 2024-01-30 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Final_project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='v_c',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='v_status',
        ),
    ]
