# Generated by Django 5.0.1 on 2024-01-30 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Final_project', '0002_remove_customer_v_c_remove_customer_v_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='v_c',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='v_status',
        ),
    ]
